name: portolio_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  image_picker: ^1.0.2
  visibility_detector: ^0.4.0+2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  fluttertoast: ^8.2.2
  firebase_storage: ^11.2.5
  firebase_database: ^10.2.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  syncfusion_flutter_pdfviewer: ^21.2.9

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/images/

